=== ribeirux/jalphanode/core/src/main/resources/schema/jalphanode-config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns="urn:jalphanode:config"
	targetNamespace="urn:jalphanode:config" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified" 
	version="1.0">

	<xs:element name="jalphanode" type="jalphanodeConfiguration" />

	<xs:complexType name="jalphanodeConfiguration">
		<xs:sequence>
			<xs:element name="tasks" type="tasksType" minOccurs="0" />
			<xs:element name="taskScheduler" type="taskSchedulerType" minOccurs="0" />
			<xs:element name="asyncExecutor" type="asyncExecutorType" minOccurs="0" />
			<xs:element name="membership" type="membershipType" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="properties">
		<xs:sequence>
			<xs:element name="property" type="property" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="property">
		<xs:attribute name="name" use="required" type="xs:string" />
		<xs:attribute name="value" use="required" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="tasksType">
		<xs:sequence>
			<xs:element name="task" type="taskType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="taskType">
		<xs:sequence>
			<xs:element name="trigger" type="triggerType" />
			<xs:element name="properties" type="properties" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="class" use="required" type="xs:string" />
		<xs:attribute name="taskName" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="triggerType">
		<xs:sequence>
			<xs:element name="expression" type="xs:string" />
			<xs:element name="timezone" type="xs:string" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="taskSchedulerType">
		<xs:sequence>
			<xs:element name="properties" type="properties" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="corePoolSize" type="oneOrMore" />
	</xs:complexType>

	<xs:complexType name="asyncExecutorType">
		<xs:sequence>
			<xs:element name="properties" type="properties" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="corePoolSize" type="oneOrMore" />
	</xs:complexType>

	<xs:complexType name="membershipType">
		<xs:sequence>
			<xs:element name="properties" type="properties" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="nodeName" type="xs:string" />
		<xs:attribute name="clusterName" type="xs:string" />
	</xs:complexType>

	<xs:simpleType name="oneOrMore">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== ribeirux/jalphanode/core/src/test/resources/good-jalphanode-config.xml
<?xml version="1.0" encoding="utf-8"?>
<jalphanode xmlns="urn:jalphanode:config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="urn:jalphanode:config https://raw.github.com/ribeirux/jalphanode/master/core/src/main/resources/schema/jalphanode-config.xsd">
    
    <tasks>
    	<task class="org.jalphanode.config.TestTask" taskName="TestName">
    		<trigger>
    			<expression>10 1 * * * ?</expression>
    			<timezone>Europe/Lisbon</timezone>
    		</trigger>
    		<properties>
            	<property name="name" value="value" />
        	</properties>
   	 	</task>
    </tasks>
    
    <taskScheduler poolSize="5">
    	<properties>
    		<property name="threadNamePrefix" value="task-pool" />
    		<property name="threadPriority" value="5" />
    	</properties>
    </taskScheduler>
    
    <asyncNotificationExecutor poolSize="5">
    	<properties>
            <property name="threadNamePrefix" value="async-pool" />
            <property name="threadPriority" value="5" />
        </properties>
    </asyncNotificationExecutor>
    
    <membership nodeName="nodeName" clusterName="clusterName">
        <properties>
            <property name="configurationFile" value="jgroups-udp.xml" />
        </properties>
    </membership>
</jalphanode>

=== ribeirux/jalphanode/demo/etc/jalphanode-config.xml
<?xml version="1.0" encoding="utf-8"?>
<jalphanode xmlns="urn:jalphanode:config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:jalphanode:config https://raw.github.com/ribeirux/jalphanode/master/core/src/main/resources/schema/jalphanode-config.xsd">

    <tasks>
        <task class="org.jalphanode.demo.HelloWorld" taskName="task-1">
            <trigger>
                <expression>*/1 * * * * *</expression>
                <timezone>Europe/Berlin</timezone>
            </trigger>
        </task>
        <task class="org.jalphanode.demo.HelloWorld" taskName="task-2">
            <trigger>
                <expression>*/2 * * * * *</expression>
                <timezone>Europe/Berlin</timezone>
            </trigger>
        </task>
        <task class="org.jalphanode.demo.HelloWorld" taskName="task-3">
            <trigger>
                <expression>*/4 * * * * *</expression>
                <timezone>Europe/Berlin</timezone>
            </trigger>
        </task>
        <task class="org.jalphanode.demo.Questions" taskName="questions">
            <trigger>
                <expression>0 0 16 * * *</expression>
                <timezone>Europe/Berlin</timezone>
            </trigger>
        </task>
    </tasks>

    <taskScheduler poolSize="5">
        <properties>
            <property name="threadPrefix" value="task-pool" />
            <property name="threadPriority" value="5" />
        </properties>
    </taskScheduler>

    <asyncNotificationExecutor poolSize="5">
        <properties>
            <property name="threadPrefix" value="async-pool" />
            <property name="threadPriority" value="5" />
        </properties>
    </asyncNotificationExecutor>

    <membership nodeName="${NODE_NAME}" clusterName="clusterName">
        <properties>
            <property name="configurationFile" value="jgroups-udp.xml" />
        </properties>
    </membership>
</jalphanode>

=== ribeirux/jalphanode/etc/jalphanode-config.xml
<?xml version="1.0" encoding="utf-8"?>
<jalphanode xmlns="urn:jalphanode:config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:jalphanode:config https://raw.github.com/ribeirux/jalphanode/master/core/src/main/resources/schema/jalphanode-config.xsd">

    <tasks>
        <task class="org.jalphanode.task.NoTask" taskName="task-1">
            <trigger>
                <expression>*/1 * * * * ?</expression>
                <timezone>Europe/Lisbon</timezone>
            </trigger>
        </task>
        <task class="org.jalphanode.task.NoTask" taskName="task-2">
            <trigger>
                <expression>*/1 * * * * ?</expression>
                <timezone>Europe/Lisbon</timezone>
            </trigger>
        </task>
        <task class="org.jalphanode.task.NoTask" taskName="task-3">
            <trigger>
                <expression>*/1 * * * * ?</expression>
                <timezone>Europe/Lisbon</timezone>
            </trigger>
        </task>
        <task class="org.jalphanode.task.NoTask" taskName="task-4">
            <trigger>
                <expression>*/1 * * * * ?</expression>
                <timezone>Europe/Lisbon</timezone>
            </trigger>
        </task>
    </tasks>

    <taskScheduler poolSize="5">
        <properties>
            <property name="threadPrefix" value="task-pool" />
            <property name="threadPriority" value="5" />
        </properties>
    </taskScheduler>

    <asyncNotificationExecutor poolSize="5">
        <properties>
            <property name="threadPrefix" value="async-pool" />
            <property name="threadPriority" value="5" />
        </properties>
    </asyncNotificationExecutor>

    <membership nodeName="nodeName" clusterName="clusterName">
        <properties>
            <property name="configurationFile" value="jgroups-udp.xml" />
        </properties>
    </membership>
</jalphanode>
